const WS = {
    CONNECTION: 'connection',
    DISCONNECT: 'disconnect',
    FC_CLIENT_CONNECT: 'FC_CLIENT_CONNECT',
    FS_CLIENT_CONNECT: 'FS_CLIENT_CONNECT',
    FC_NEW_MESSAGE: 'FC_NEW_MESSAGE',
    FS_NEW_MESSAGE: 'FS_NEw_MESSAGE',
    FC_CLIENT_DISCONNECT: 'FC_CLIENT_DISCONNECT',
    FS_CLIENT_DISCONNECT: 'FS_CLIENT_DISCONNECT',
};

module.exports = WS;
